name: flutter_custom_creator
description: A custom Flutter project creator.
version: 1.0.1
homepage: https://github.com/flutter-try-catch/flutter_custom_creator

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  yaml: ^3.1.0
  yaml_edit: ^2.0.3
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

executables:
  flutter_custom_creator: